environment: development
node:
  callsign: 'KJ4KPY'
  website: 'https://www.henrycountyars.org'
  callsign_name: 'Henry County Amateur Radio Society'
  location: 'Henry County, GA'
  grid_square: 'EM73vl'
server:
  port: 8080
  host: 0.0.0.0
asterisk:
  port: '5038'
  host: '127.0.0.1'
  username: 'admin'
  password: 'xxxxx'
  events: true